# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_description', models.TextField(max_length=200)),
                ('project_hours', models.IntegerField(default=0)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='timekeeper.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Timecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timecard_owner', models.CharField(max_length=50)),
                ('timecard_project', models.CharField(max_length=50)),
                ('timecard_date', models.DateField()),
                ('timecard_hours', models.IntegerField()),
            ],
        ),
    ]
