# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('cost', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('project_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='timekeeper.ProjectTask')),
            ],
        ),
    ]
