# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timekeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='supervisors',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
