# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='timecard_expenditure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timecard',
            name='timecard_expenditure_desc',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
