# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ManyToManyField(to='timekeeper.Client'),
        ),
    ]
