# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0002_auto_20170720_1056'),
        ('timekeeper', '0002_auto_20170721_1009'),
    ]

    operations = [
    ]
