# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0002_projectexpenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hourly',
            field=models.FloatField(null=True),
        ),
    ]
