# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
