# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 23:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0002_project_supervisors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='supervisors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
