# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0002_auto_20170615_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timekeeper.Client'),
        ),
    ]
