# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0002_auto_20170705_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='project_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timekeeper.ProjectTask'),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='timecard_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timekeeper.Project'),
        ),
    ]
