# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0003_auto_20170612_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
