# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 00:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0003_auto_20170615_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='timecard_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='timecard_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='timecard_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timekeeper.Project'),
        ),
    ]
