# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0003_auto_20170626_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='supervisors',
            new_name='employees',
        ),
    ]
