# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0003_userprofile_hourly'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpenditure',
            name='markup',
            field=models.FloatField(default=0, null=True),
        ),
    ]
