# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0003_auto_20170725_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='timecard_expenditure',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
