# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0004_projectexpenditure_markup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectexpenditure',
            name='markup',
        ),
        migrations.AddField(
            model_name='project',
            name='labor_markup',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='material_markup',
            field=models.FloatField(default=0, null=True),
        ),
    ]
