# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0004_auto_20170615_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='flat_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='running_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='timecard',
            name='timecard_charge',
            field=models.FloatField(default=0),
        ),
    ]
