# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0004_auto_20170628_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
