# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0005_auto_20170725_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecard',
            name='timecard_expenditure',
        ),
    ]
