# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0006_remove_timecard_timecard_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='timecard_expenditure',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
