# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 14:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0006_auto_20170707_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='project_task',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='timecard_project', chained_model_field='project_task_link', on_delete=django.db.models.deletion.CASCADE, to='timekeeper.ProjectTask'),
        ),
    ]
