# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0007_timecard_timecard_expenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='timecard_expenditure',
            field=models.IntegerField(default=0),
        ),
    ]
